from rich.table import Table
from rich import print as xprint


def main_help():
    main_help_table = Table(show_header=True, header_style="bold white")
    main_help_table.add_column("Command", style="dim")
    main_help_table.add_column("Description")
    main_help_table.add_row("help", "Show this menu")
    main_help_table.add_row("exit", "Exit to C2 server prompt (Shell works in background)")
    main_help_table.add_row("clear", "Clear the previous outputs")
    main_help_table.add_row("terminate", "Exit the shell completely")
    main_help_table.add_section()
    main_help_table.add_row("cd", "Change directory")
    main_help_table.add_row("pwd", "Print current working directory")
    main_help_table.add_row("mkdir *dir_name*", "Create a specified directory")
    main_help_table.add_row("rm *dir_name*", "Delete a specified directory")
    main_help_table.add_row("powershell <command>", "Run powershell command")
    main_help_table.add_row("start *exe_name*", "Start a specified executable")
    main_help_table.add_section()
    main_help_table.add_row("env", "Check environment variables")
    main_help_table.add_row("sc", "List all running services")
    main_help_table.add_row("user", "Current user")
    main_help_table.add_row("info", "Get all information about compromised system")
    main_help_table.add_row("av", "List all antivirus(es) in compromised system")
    main_help_table.add_section()
    main_help_table.add_row("download *file_name*", "Download files from compromised system")
    main_help_table.add_row("upload *file_name*", "Upload files to compromised system")
    main_help_table.add_section()
    main_help_table.add_row("persistence1", "Persistence via Method 1")
    main_help_table.add_row("persistence2", "Persistence via Method 2")
    main_help_table.add_row("get", "Dump all stored passwords from Chrome browser")
    main_help_table.add_row("chrome_pass_dump", "Delete a specified directory")
    main_help_table.add_row("wifi_password", "Dump passwords of all saved Wifi networks")
    main_help_table.add_row("keylogger", "Start keylogger")
    main_help_table.add_row("dump_keylogger", "Dump all logs done by keylogger")
    main_help_table.add_row("python_install", "Install Python on compromised pc without UI")
    xprint(main_help_table)


def session_help():
    session_help_commands_table = Table(show_header=True, header_style="bold white")
    session_help_commands_table.add_column("Command", style="dim", width=12)
    session_help_commands_table.add_column("Description")
    session_help_commands_table.add_row("sessions -l", "List all victims connected to C2 server")
    session_help_commands_table.add_row("sessions -i <session number>", "Interact with a session individually")
    session_help_commands_table.add_row("sendall", "Send the same command to all victims")
    session_help_commands_table.add_row("shell_help", "All commands before/after getting shell")
    xprint(session_help_commands_table)
    
